# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 648b6861c5b012280968385dbf34701d1accc18eda9ea95e25f539eca84db8b81758c6fe2f28a62ffc35208f932b3eca188a16f5e4145895d648509f15fdf8e4

test:
  secret_key_base: 4e003401200f96b5efafe7837d114b7645d13753f1c8a2851efce39a72636cf742468f848d0ee3570fa358a48c15c50b792edd93b3354b7b8647079c8f4db405

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
